services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rota-manager
    networks:
      proxy:

  rota-manager:
    image: kierenlgr/rota-manager
    restart: "always"
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
      JWT_SECRET: ${JWT_SECRET}
      POSTMARK_AUTH_TOKEN: ${POSTMARK_AUTH_TOKEN}
      POSTMARK_EMAIL_SENDER_ADDRESS: ${POSTMARK_EMAIL_SENDER_ADDRESS}
    depends_on:
      - db
    networks:
      proxy:

  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      proxy:

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      proxy:

networks:
  proxy:

volumes:
  db:
    driver: local

